server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chhan
    username: chhan
    password: 190814

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true